spring.application.name=notification-service
server.port=8087

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# RabbitMQ Configuration
rabbitmq.exchange=railnova-exchange
rabbitmq.queue=payment-notification-queue
rabbitmq.routingKey=payment.success

# Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized