-- Comprehensive Coach and Seat Data for RailNova
-- Run this in MySQL on train_db (port 3306)
-- This adds coaches and seats for all existing journeys

USE train_db;

-- First, let's see what journeys we have
SELECT 'Current journeys in database:' AS info, COUNT(*) AS count FROM journey;

-- Coach insertion for different train types
-- We'll create coaches for each journey based on train type and fare availability

-- Helper: Get journey IDs and their train types for coach configuration
SELECT 'Journey and Train mapping:' AS info;
SELECT j.id as journey_id, j.train_id, t.name as train_name, t.train_number
FROM journey j 
JOIN train t ON j.train_id = t.id 
ORDER BY j.id 
LIMIT 10;

-- Insert Coaches for Premium Trains (Rajdhani, Shatabdi, Duronto)
-- These trains have AC_1_TIER, AC_2_TIER, AC_3_TIER coaches

-- Rajdhani Express Coaches (Train IDs 6, 7, 8, 9)
INSERT IGNORE INTO coach (journey_id, coach_number, coach_type) 
SELECT j.id, 'H1', 'AC_1_TIER' FROM journey j WHERE j.train_id IN (6, 7, 8, 9)
UNION ALL
SELECT j.id, 'A1', 'AC_2_TIER' FROM journey j WHERE j.train_id IN (6, 7, 8, 9)
UNION ALL
SELECT j.id, 'A2', 'AC_2_TIER' FROM journey j WHERE j.train_id IN (6, 7, 8, 9)
UNION ALL
SELECT j.id, 'B1', 'AC_3_TIER' FROM journey j WHERE j.train_id IN (6, 7, 8, 9)
UNION ALL
SELECT j.id, 'B2', 'AC_3_TIER' FROM journey j WHERE j.train_id IN (6, 7, 8, 9)
UNION ALL
SELECT j.id, 'B3', 'AC_3_TIER' FROM journey j WHERE j.train_id IN (6, 7, 8, 9);

-- Shatabdi Express Coaches (Train IDs 12, 13, 14, 15) - Chair Car trains
INSERT IGNORE INTO coach (journey_id, coach_number, coach_type)
SELECT j.id, 'EC1', 'EXECUTIVE' FROM journey j WHERE j.train_id IN (12, 13, 14, 15)
UNION ALL
SELECT j.id, 'CC1', 'AC_CHAIR' FROM journey j WHERE j.train_id IN (12, 13, 14, 15)
UNION ALL
SELECT j.id, 'CC2', 'AC_CHAIR' FROM journey j WHERE j.train_id IN (12, 13, 14, 15)
UNION ALL
SELECT j.id, 'CC3', 'AC_CHAIR' FROM journey j WHERE j.train_id IN (12, 13, 14, 15);

-- Duronto Express Coaches (Train IDs 16, 17, 18, 19)
INSERT IGNORE INTO coach (journey_id, coach_number, coach_type)
SELECT j.id, 'H1', 'AC_1_TIER' FROM journey j WHERE j.train_id IN (16, 17, 18, 19)
UNION ALL
SELECT j.id, 'A1', 'AC_2_TIER' FROM journey j WHERE j.train_id IN (16, 17, 18, 19)
UNION ALL
SELECT j.id, 'A2', 'AC_2_TIER' FROM journey j WHERE j.train_id IN (16, 17, 18, 19)
UNION ALL
SELECT j.id, 'B1', 'AC_3_TIER' FROM journey j WHERE j.train_id IN (16, 17, 18, 19)
UNION ALL
SELECT j.id, 'B2', 'AC_3_TIER' FROM journey j WHERE j.train_id IN (16, 17, 18, 19);

-- Tamil Nadu Express Coaches (Train IDs 10, 11) - Full service train
INSERT IGNORE INTO coach (journey_id, coach_number, coach_type)
SELECT j.id, 'H1', 'AC_1_TIER' FROM journey j WHERE j.train_id IN (10, 11)
UNION ALL
SELECT j.id, 'A1', 'AC_2_TIER' FROM journey j WHERE j.train_id IN (10, 11)
UNION ALL
SELECT j.id, 'A2', 'AC_2_TIER' FROM journey j WHERE j.train_id IN (10, 11)
UNION ALL
SELECT j.id, 'B1', 'AC_3_TIER' FROM journey j WHERE j.train_id IN (10, 11)
UNION ALL
SELECT j.id, 'B2', 'AC_3_TIER' FROM journey j WHERE j.train_id IN (10, 11)
UNION ALL
SELECT j.id, 'S1', 'SLEEPER' FROM journey j WHERE j.train_id IN (10, 11)
UNION ALL
SELECT j.id, 'S2', 'SLEEPER' FROM journey j WHERE j.train_id IN (10, 11)
UNION ALL
SELECT j.id, 'S3', 'SLEEPER' FROM journey j WHERE j.train_id IN (10, 11);

-- Garib Rath Coaches (Train IDs 20, 21, 22, 23) - Only AC_3_TIER
INSERT IGNORE INTO coach (journey_id, coach_number, coach_type)
SELECT j.id, 'B1', 'AC_3_TIER' FROM journey j WHERE j.train_id IN (20, 21, 22, 23)
UNION ALL
SELECT j.id, 'B2', 'AC_3_TIER' FROM journey j WHERE j.train_id IN (20, 21, 22, 23)
UNION ALL
SELECT j.id, 'B3', 'AC_3_TIER' FROM journey j WHERE j.train_id IN (20, 21, 22, 23)
UNION ALL
SELECT j.id, 'B4', 'AC_3_TIER' FROM journey j WHERE j.train_id IN (20, 21, 22, 23);

-- Jan Shatabdi Coaches (Train IDs 24, 25, 26, 27) - Chair Car
INSERT IGNORE INTO coach (journey_id, coach_number, coach_type)
SELECT j.id, 'CC1', 'AC_CHAIR' FROM journey j WHERE j.train_id IN (24, 25, 26, 27)
UNION ALL
SELECT j.id, 'CC2', 'AC_CHAIR' FROM journey j WHERE j.train_id IN (24, 25, 26, 27)
UNION ALL
SELECT j.id, 'C1', 'CC' FROM journey j WHERE j.train_id IN (24, 25, 26, 27)
UNION ALL
SELECT j.id, 'C2', 'CC' FROM journey j WHERE j.train_id IN (24, 25, 26, 27);

-- Long Distance Express Trains (Train IDs 30-55) - Mixed coaches
INSERT IGNORE INTO coach (journey_id, coach_number, coach_type)
SELECT j.id, 'A1', 'AC_2_TIER' FROM journey j WHERE j.train_id BETWEEN 30 AND 55
UNION ALL
SELECT j.id, 'A2', 'AC_2_TIER' FROM journey j WHERE j.train_id BETWEEN 30 AND 55
UNION ALL
SELECT j.id, 'B1', 'AC_3_TIER' FROM journey j WHERE j.train_id BETWEEN 30 AND 55
UNION ALL
SELECT j.id, 'B2', 'AC_3_TIER' FROM journey j WHERE j.train_id BETWEEN 30 AND 55
UNION ALL
SELECT j.id, 'S1', 'SLEEPER' FROM journey j WHERE j.train_id BETWEEN 30 AND 55
UNION ALL
SELECT j.id, 'S2', 'SLEEPER' FROM journey j WHERE j.train_id BETWEEN 30 AND 55
UNION ALL
SELECT j.id, 'S3', 'SLEEPER' FROM journey j WHERE j.train_id BETWEEN 30 AND 55;

-- Special case: Add AC_1_TIER for premium long distance trains
INSERT IGNORE INTO coach (journey_id, coach_number, coach_type)
SELECT j.id, 'H1', 'AC_1_TIER' FROM journey j WHERE j.train_id IN (28, 29, 30, 31, 32, 33, 40, 41, 42, 43, 46, 47);

-- Check coach insertion
SELECT 'Total coaches inserted:' AS info, COUNT(*) AS count FROM coach;

-- Now insert seats for each coach type
-- AC_1_TIER: 18 seats per coach (1A-18A, 1B-18B)
INSERT IGNORE INTO seat (coach_id, seat_number, status)
SELECT c.id, CONCAT(s.seat_num, 'A'), 'AVAILABLE'
FROM coach c
CROSS JOIN (
    SELECT 1 as seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION 
    SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION 
    SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18
) s
WHERE c.coach_type = 'AC_1_TIER'
UNION ALL
SELECT c.id, CONCAT(s.seat_num, 'B'), 'AVAILABLE'
FROM coach c
CROSS JOIN (
    SELECT 1 as seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION 
    SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION 
    SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18
) s
WHERE c.coach_type = 'AC_1_TIER';

-- AC_2_TIER: 48 seats per coach (1A-24A, 1B-24B)
INSERT IGNORE INTO seat (coach_id, seat_number, status)
SELECT c.id, CONCAT(s.seat_num, 'A'), 'AVAILABLE'
FROM coach c
CROSS JOIN (
    SELECT 1 as seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION 
    SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION 
    SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION
    SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24
) s
WHERE c.coach_type = 'AC_2_TIER'
UNION ALL
SELECT c.id, CONCAT(s.seat_num, 'B'), 'AVAILABLE'
FROM coach c
CROSS JOIN (
    SELECT 1 as seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION 
    SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION 
    SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION
    SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24
) s
WHERE c.coach_type = 'AC_2_TIER';

-- AC_3_TIER: 72 seats per coach (1A-24A, 1B-24B, 1C-24C)
INSERT IGNORE INTO seat (coach_id, seat_number, status)
SELECT c.id, CONCAT(s.seat_num, 'A'), 'AVAILABLE'
FROM coach c
CROSS JOIN (
    SELECT 1 as seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION 
    SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION 
    SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION
    SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24
) s
WHERE c.coach_type = 'AC_3_TIER'
UNION ALL
SELECT c.id, CONCAT(s.seat_num, 'B'), 'AVAILABLE'
FROM coach c
CROSS JOIN (
    SELECT 1 as seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION 
    SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION 
    SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION
    SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24
) s
WHERE c.coach_type = 'AC_3_TIER'
UNION ALL
SELECT c.id, CONCAT(s.seat_num, 'C'), 'AVAILABLE'
FROM coach c
CROSS JOIN (
    SELECT 1 as seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION 
    SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION 
    SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION
    SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24
) s
WHERE c.coach_type = 'AC_3_TIER';

-- SLEEPER: 72 seats per coach (1A-24A, 1B-24B, 1C-24C)
INSERT IGNORE INTO seat (coach_id, seat_number, status)
SELECT c.id, CONCAT(s.seat_num, 'A'), 'AVAILABLE'
FROM coach c
CROSS JOIN (
    SELECT 1 as seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION 
    SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION 
    SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION
    SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24
) s
WHERE c.coach_type = 'SLEEPER'
UNION ALL
SELECT c.id, CONCAT(s.seat_num, 'B'), 'AVAILABLE'
FROM coach c
CROSS JOIN (
    SELECT 1 as seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION 
    SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION 
    SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION
    SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24
) s
WHERE c.coach_type = 'SLEEPER'
UNION ALL
SELECT c.id, CONCAT(s.seat_num, 'C'), 'AVAILABLE'
FROM coach c
CROSS JOIN (
    SELECT 1 as seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION 
    SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION 
    SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION
    SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24
) s
WHERE c.coach_type = 'SLEEPER';

-- AC_CHAIR: 78 seats per coach (1A-39A, 1B-39B)
INSERT IGNORE INTO seat (coach_id, seat_number, status)
SELECT c.id, CONCAT(s.seat_num, 'A'), 'AVAILABLE'
FROM coach c
CROSS JOIN (
    SELECT 1 as seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION 
    SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION 
    SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION
    SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION
    SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION
    SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION SELECT 36 UNION
    SELECT 37 UNION SELECT 38 UNION SELECT 39
) s
WHERE c.coach_type = 'AC_CHAIR'
UNION ALL
SELECT c.id, CONCAT(s.seat_num, 'B'), 'AVAILABLE'
FROM coach c
CROSS JOIN (
    SELECT 1 as seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION 
    SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION 
    SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION
    SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION
    SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION
    SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION SELECT 36 UNION
    SELECT 37 UNION SELECT 38 UNION SELECT 39
) s
WHERE c.coach_type = 'AC_CHAIR';

-- EXECUTIVE: 56 seats per coach (1A-28A, 1B-28B) - More spacious
INSERT IGNORE INTO seat (coach_id, seat_number, status)
SELECT c.id, CONCAT(s.seat_num, 'A'), 'AVAILABLE'
FROM coach c
CROSS JOIN (
    SELECT 1 as seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION 
    SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION 
    SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION
    SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION
    SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28
) s
WHERE c.coach_type = 'EXECUTIVE'
UNION ALL
SELECT c.id, CONCAT(s.seat_num, 'B'), 'AVAILABLE'
FROM coach c
CROSS JOIN (
    SELECT 1 as seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION 
    SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION 
    SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION
    SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION
    SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28
) s
WHERE c.coach_type = 'EXECUTIVE';

-- CC (Chair Car): 104 seats per coach (1A-52A, 1B-52B)
INSERT IGNORE INTO seat (coach_id, seat_number, status)
SELECT c.id, CONCAT(s.seat_num, 'A'), 'AVAILABLE'
FROM coach c
CROSS JOIN (
    SELECT 1 as seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION 
    SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION 
    SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION
    SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION
    SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION
    SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION SELECT 36 UNION
    SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40 UNION SELECT 41 UNION SELECT 42 UNION
    SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION
    SELECT 49 UNION SELECT 50 UNION SELECT 51 UNION SELECT 52
) s
WHERE c.coach_type = 'CC'
UNION ALL
SELECT c.id, CONCAT(s.seat_num, 'B'), 'AVAILABLE'
FROM coach c
CROSS JOIN (
    SELECT 1 as seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION 
    SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION 
    SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION
    SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION
    SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION
    SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION SELECT 36 UNION
    SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40 UNION SELECT 41 UNION SELECT 42 UNION
    SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION
    SELECT 49 UNION SELECT 50 UNION SELECT 51 UNION SELECT 52
) s
WHERE c.coach_type = 'CC';

-- Add some realistic booking patterns (some seats booked/locked)
-- Book 10-15% of seats randomly
UPDATE seat SET status = 'BOOKED' 
WHERE id IN (
    SELECT id FROM (
        SELECT id FROM seat 
        WHERE RAND() < 0.12 
        ORDER BY RAND() 
        LIMIT 1000
    ) AS random_seats
);

-- Lock 2-3% of seats (temporary holds)
UPDATE seat SET status = 'LOCKED' 
WHERE status = 'AVAILABLE' AND id IN (
    SELECT id FROM (
        SELECT id FROM seat 
        WHERE status = 'AVAILABLE' AND RAND() < 0.025
        ORDER BY RAND() 
        LIMIT 200
    ) AS random_locked_seats
);

-- Final Summary
SELECT 'COACH AND SEAT DATA SUMMARY' AS '=== SUMMARY ===';
SELECT 'Total coaches:' AS metric, COUNT(*) AS value FROM coach
UNION ALL
SELECT 'Total seats:' AS metric, COUNT(*) AS value FROM seat
UNION ALL
SELECT 'Available seats:' AS metric, COUNT(*) AS value FROM seat WHERE status = 'AVAILABLE'
UNION ALL
SELECT 'Booked seats:' AS metric, COUNT(*) AS value FROM seat WHERE status = 'BOOKED'
UNION ALL
SELECT 'Locked seats:' AS metric, COUNT(*) AS value FROM seat WHERE status = 'LOCKED';

-- Coach type breakdown
SELECT 'Coach types breakdown:' AS info;
SELECT coach_type, COUNT(*) as coach_count, 
       (SELECT COUNT(*) FROM seat WHERE seat.coach_id = coach.id) as total_seats
FROM coach 
GROUP BY coach_type 
ORDER BY coach_type;

-- Sample data verification
SELECT 'Sample coach and seat data:' AS info;
SELECT c.id as coach_id, c.coach_number, c.coach_type, c.journey_id,
       COUNT(s.id) as seat_count,
       SUM(CASE WHEN s.status = 'AVAILABLE' THEN 1 ELSE 0 END) as available_seats,
       SUM(CASE WHEN s.status = 'BOOKED' THEN 1 ELSE 0 END) as booked_seats
FROM coach c
LEFT JOIN seat s ON c.id = s.coach_id
GROUP BY c.id, c.coach_number, c.coach_type, c.journey_id
ORDER BY c.journey_id, c.coach_number
LIMIT 20;

SELECT 'Coach and seat data insertion completed successfully!' AS Status;